### ISSUE TITLE
Error with database configuration

### ISSUE THREAD

**Issue by kkoci** [websitescenes/pushvendor#18]
Hi

I cloned your project, seems really interesting to get started on this kind of apps on RoR.

However, I ran 'bundle install' command, everything seems fine, until I try 'rails s'

See this traceback:

kkoci@debian:~/rails_pos/pushvendor/bin$ rails server    
    => Booting WEBrick
    => Rails 4.0.1 application starting in development on http://0.0.0.0:3000
    => Run `rails server -h` for more startup options
    => Ctrl-C to shutdown server
    Exiting
    /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.1/lib/rails/application/configuration.rb:110:in `database_configuration': Could not load database configuration. No such file - /home/kkoci/rails_pos/pushvendor/config/database.yml (RuntimeError)
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.1/lib/active_record/railtie.rb:175:in `block (2 levels) in <class:Railtie>'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.0.1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.0.1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.0.1/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.0.1/lib/active_support/lazy_load_hooks.rb:27:in `each'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.0.1/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.1/lib/active_record/railtie.rb:174:in `block in <class:Railtie>'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.1/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.1/lib/rails/initializable.rb:30:in `run'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/kkoci/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
        from /home/kkoci/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
        from /home/kkoci/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
        from /home/kkoci/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
        from /home/kkoci/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:180:in `each'
        from /home/kkoci/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
        from /home/kkoci/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.1/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.1/lib/rails/application.rb:215:in `initialize!'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.1/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /home/kkoci/rails_pos/pushvendor/config/environment.rb:5:in `<top (required)>'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `block in require'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:214:in `load_dependency'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
        from /home/kkoci/rails_pos/pushvendor/config.ru:3:in `block in <main>'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
        from /home/kkoci/rails_pos/pushvendor/config.ru:in `new'
        from /home/kkoci/rails_pos/pushvendor/config.ru:in `<main>'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.5.5/lib/rack/builder.rb:49:in `eval'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.5.5/lib/rack/builder.rb:49:in `new_from_string'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.5.5/lib/rack/builder.rb:40:in `parse_file'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.5.5/lib/rack/server.rb:277:in `build_app_and_options_from_config'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.5.5/lib/rack/server.rb:199:in `app'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.1/lib/rails/commands/server.rb:48:in `app'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.5.5/lib/rack/server.rb:314:in `wrapped_app'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.1/lib/rails/commands/server.rb:75:in `start'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.1/lib/rails/commands.rb:76:in `block in <top (required)>'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.1/lib/rails/commands.rb:71:in `tap'
        from /home/kkoci/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.1/lib/rails/commands.rb:71:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

I guess I need that database.yml, tried 'rails g' but nothing, could you help, please?

**Comment by kkoci** [comment]
Solved, sorry for the inconvenience =)

**Comment by websitescenes** [comment]
Sorry this project is kind of a mess. Started it and then stopped working on it because I started a commercial version.
